# Generated by Django 3.0.5 on 2023-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
